class AppStrings {
  static final Map<String, Map<String, String>> _strings = {
    'en': {
      'appTitle': 'Health Hearts at Home',
      'home': 'Home',
      'generalChildcare': 'General Childcare',
      'tutorials': 'Tutorials',
      'spiritual': 'Spiritual Needs',
      'hospitalInfo': 'Hospital Information',
      'caregiverSupport': 'Caregiver Support',
      'trackChild': 'Track Your Child',
      'aboutCHD': 'About Your Child\'s CHD',
      'contacts': 'Contacts',
      'back': 'Back',
      'language': 'Language',
      'logout': 'Logout',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'close': 'Close',
      'weight': 'Weight (kg)',
      'feedingAmount': 'Feeding Amount (ml)',
      'feedingType': 'Feeding Type',
      'oxygenSaturation': 'Oxygen Saturation (%)',
      'equipment': 'Equipment Used',
      'notes': 'Notes',
      'date': 'Date',
      'time': 'Time',
      'breast': 'Breast',
      'bottle': 'Bottle',
      'hospitalName': 'X University Hospital',
      'hospitalPhone': 'Phone: +1 (XXX) XXX-XXXX',
      'hospitalEmail': 'Email: info@xuhosp.com',
      'hospitalWebsite': 'Website: www.xuhosp.com',
      'cafeteriaHours': 'Cafeteria Hours: 6AM - 8PM',
      'hospitalMap': 'Hospital Map',
      'showerAvailability': 'Shower Availability',
      'emergencyContact': 'Emergency Contact',
      'supportResources': 'Support Resources',
      'patientStories': 'Patient Stories',
      'devotionals': 'Devotionals',
      'chapelServices': 'Chapel Services',
      'errorLoading': 'Error loading content',
      'tryAgain': 'Try Again',
      'noData': 'No data available',
      'welcome': 'Welcome',
      'updateChild': 'Update Child Information',
      'childInfo': 'Child Information',
    },
    'ar': {
      'appTitle': 'قلوب صحية في البيت',
      'home': 'الرئيسية',
      'generalChildcare': 'العناية العامة بالأطفال',
      'tutorials': 'دروس تعليمية',
      'spiritual': 'الاحتياجات الروحية',
      'hospitalInfo': 'معلومات المستشفى',
      'caregiverSupport': 'دعم مقدمي الرعاية',
      'trackChild': 'تتبع طفلك',
      'aboutCHD': 'حول أمراض القلب الخلقية',
      'contacts': 'جهات الاتصال',
      'back': 'رجوع',
      'language': 'اللغة',
      'logout': 'تسجيل الخروج',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'close': 'إغلاق',
      'weight': 'الوزن (كجم)',
      'feedingAmount': 'كمية الرضاعة (مل)',
      'feedingType': 'نوع الرضاعة',
      'oxygenSaturation': 'تشبع الأكسجين (%)',
      'equipment': 'المعدات المستخدمة',
      'notes': 'ملاحظات',
      'date': 'التاريخ',
      'time': 'الوقت',
      'breast': 'الثدي',
      'bottle': 'الزجاجة',
      'hospitalName': 'مستشفى جامعة X',
      'hospitalPhone': 'الهاتف: +1 (XXX) XXX-XXXX',
      'hospitalEmail': 'البريد الإلكتروني: info@xuhosp.com',
      'hospitalWebsite': 'الموقع: www.xuhosp.com',
      'cafeteriaHours': 'ساعات المقهى: 6 صباحاً - 8 مساءً',
      'hospitalMap': 'خريطة المستشفى',
      'showerAvailability': 'توفر الدش',
      'emergencyContact': 'جهات الاتصال الطارئة',
      'supportResources': 'موارد الدعم',
      'patientStories': 'قصص المرضى',
      'devotionals': 'الألحان الدينية',
      'chapelServices': 'خدمات الكنيسة',
      'errorLoading': 'خطأ في تحميل المحتوى',
      'tryAgain': 'حاول مرة أخرى',
      'noData': 'لا توجد بيانات متاحة',
      'welcome': 'أهلا وسهلا',
      'updateChild': 'تحديث معلومات الطفل',
      'childInfo': 'معلومات الطفل',
    },
  };

  static String get(String key, String language) {
    return _strings[language]?[key] ?? _strings['en']?[key] ?? key;
  }
}
